### ISSUE TITLE
[UI] As a user, I can see the Home screen after logged in successfully

### ISSUE THREAD

**Issue by luongvo** [luongvo/flutter-survey#11]
## Why

After logged in, the user can see the Home screen with the survey list.

## Acceptance Criteria

- Show the horizontal list with the item detail as:
  - Show the date-time on the left corner
  - Show the avatar on the right
  - Show the indicator
  - Show the title and description
  - Show the arrow button

Design: https://www.figma.com/proto/GjRPOjDyZ6f4EDL3wKarRK/Challenge---Mobile-App?node-id=44%3A148&scaling=scale-down

![image](https://user-images.githubusercontent.com/16315358/119629601-5cd76c80-be38-11eb-863c-300d04f1c456.png)

**Comment by sleepylee** [comment]
when I worked on this screen, there is a similar thought but here is the catch: 
- the top bar (avatar + date time) is actually always staying statically -> so it's better that we implement it separate to this screen.
- The bottom part + the background is actually loaded from the Surveys - so think in an Android way, you may want to have a ViewPager-liked implementation separately.

2 tickets here will make your life easier with the corresponding PRs. How do you think?
