### ISSUE TITLE
Setup localization

### ISSUE THREAD

**Issue by luongvo** [luongvo/flutter-survey#25]
## Why

We need to support multi-languages due to can increase our user base.
 
## Acceptance Criteria

- Support `en` language is a must
- Support the second language (`vn`, `th`) is nice have

**Comment by doannimble** [comment]
@luongvo I suggest to use i10n, use the delegate as S.delegate and get the localization like S.of(context).example instead of AppLocalizations.of(context)!.example

**Comment by luongvo** [comment]
> @luongvo I suggest to use i10n, use the delegate as S.delegate and get the localization like S.of(context).example instead of AppLocalizations.of(context)!.example

I haven't try to use i10n yet, but what are the advantages of i10n vs in except the reference is shorter by `S.of(context).example` vs `AppLocalizations.of(context)!.example`? I'm feeling fine with i8n if there is 1 of biggest advantage 🤔

**Comment by luongvo** [comment]
@doannimble

**Comment by doannimble** [comment]
@luongvo as I'm not sure why we need to use `!` in every getting value.
I have a bit confuse. You're using i8n, right? But I dont know why your configuration named l10n on code changes.
If you use l10n with intl, it's very simple for configuration.

**Comment by luongvo** [comment]
> @luongvo as I'm not sure why we need to use `!` in every getting value.
> I have a bit confuse. You're using i8n, right? But I dont know why your configuration named l10n on code changes.
> If you use l10n with intl, it's very simple for configuration.

I'm following https://flutter.dev/docs/development/accessibility-and-localization/internationalization and it seems guide me to use `AppLocalizations` 🤔

**Comment by doannimble** [comment]
@luongvo as you can see in the last of your following link, there is a region name : Using the Dart intl tools.
Here is the good resource I know : https://www.raywenderlich.com/10794904-internationalizing-and-localizing-your-flutter-app.
For the setup, it's very simple with three steps:
- install intl plugin
- flutter_intl:
  enabled: true (on pubspec)
- update intl_[language] file with corresponding content

**Comment by luongvo** [comment]
@doannimble let me clarify some points here:

> I have a bit confuse. You're using i8n, right? But I dont know why your configuration named l10n on code changes.
If you use l10n with intl, it's very simple for configuration.

There are 3 word definitions:
- I18n - Internationalization - Providing some kind of framework so that you can easily swap out strings, graphics, sounds and other resources and generally handling different conventions of communication.
- L10n - Localization - The process of creating a bunch of strings, graphics, sounds etc. so that you can target a specific nationality, language or region.
- G11n - Globalization - Doing both Internationalization and Localization steps :)

So, I don't see any issues from what I said in the PR which I'm doing `i18n` but the config is `l10n` here. Actually `i18n` and `l10n` are not 2 different ways of configuration so we're talking on the same thing, not a new thing 🤓 

> Using the Dart intl tools. Here is the good resource I know : https://www.raywenderlich.com/10794904-internationalizing-and-localizing-your-flutter-app.

Actually, I can archive the same thing when following this article https://flutter.dev/docs/development/accessibility-and-localization/internationalization and I don't any problem. The only thing different here is the name of localization class is `S` from yours and `AppLocalizations`. I don't think a shorter class name is a huge improvement here and `AppLocalizations` looks better to me for reference.

There is 1 thing I can improve here is I can also use the generated `localizationsDelegates` and `supportedLocales` list instead of providing them manually.
```
const MaterialApp(
  title: 'Localizations Sample App',
  localizationsDelegates: AppLocalizations.localizationsDelegates,
  supportedLocales: AppLocalizations.supportedLocales,
);
```
