### ISSUE TITLE
Setup CI: Github Action

### ISSUE THREAD

**Issue by luongvo** [luongvo/flutter-survey#3]
## Why

We need a CI pipeline to automatically analyze and test all feature branches before merging.

## Acceptance Criteria

- Use Github action
- Add workflow to automatically analyze and test all feature branches before merging, which has flowing steps as below:
  - get and prepare necessary components
  - check formatting and analytic code
  - execute unit and UI tests

**Comment by olivierobert** [comment]
Why not prioritizing this into the first release `0.1.0` so that all feature PRs have tests?

I also recommend to break down into two stories: one for CI and one for CD.

**Comment by luongvo** [comment]
@olivierobert I see the concern here as I did not prioritize this from the plan. Hmm, how about delaying 0.1.0 release a bit and let me finish them today as well? 🤔

**Comment by luongvo** [comment]
I separated #45 into `0.2.0` release as that task requires effort to config build for both platforms.
